version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Начинается сборка проекта..."
      - echo "Установка зависимостей..."
  build:
    commands:
      - echo "Запуск тестов..."
      - mvn clean test -Daws.execution=true
  post_build:
    commands:
      - echo "Генерация отчёта Allure..."
      - mvn allure:report
      - echo "Копирование отчетов в S3..."
      - aws s3 cp target/site/allure-maven-plugin s3://utyfdfrthby08bucket/java-selenide/allure-reports/$(date +%Y-%m-%d_%H-%M-%S) --recursive
      - echo "Сборка завершена успешно!"

artifacts:
  files:
    - target/site/allure-maven-plugin/**/*
    - target/surefire-reports/**/*
  discard-paths: no