version: 0.2

phases:
  install:
    commands:
      - echo "Проверяем версию Maven..."
      - mvn --version
  pre_build:
    commands:
      - echo "Очистка проекта..."
      - mvn clean
  build:
    commands:
      - echo "Запуск сборки и тестов..."
      - mvn package
  post_build:
    commands:
      - echo "Сборка завершена на $(date)"
artifacts:
  files:
    - target/*.jar
    - target/surefire-reports/**/*.*
